### ISSUE TITLE
Setup.py problem

### ISSUE THREAD

**Issue by ZhaoShaw** [HHTpy/HHTpywrapper#5]
Hi!
When I run `python setup.py install`  , I get the following error. Can you help me figure out what the reason is? Thank you!!
![1212](https://user-images.githubusercontent.com/36875335/39611707-5d8dec44-4f8c-11e8-8321-53a7d6a5d9c7.png)

**Comment by ZhaoShaw** [comment]
BTW，I have already installed unrar (0.3)，unzipper (1.11)，rarfile (3.0)，pyunpack (0.1.2)，patool (1.12)，Python (3.5.4).

**Comment by YihaoSu** [comment]
Hi, ZhaoShaw,

This package works fine on Linux. However, I haven't test it on Windows.
It seems to me that the error may caused by unrar, unzipper or patool. 
Can you execute unrar, unzipper, patool command in PowerShell?

**Comment by ZhaoShaw** [comment]
Thanks for your reminder, I seem to find something.
![1212](https://user-images.githubusercontent.com/36875335/39613415-c6b478d4-4f99-11e8-83a6-ed26cd29c551.png)
I've found a problem with the ‘#find and load unrar library’ module in the unrarlib.py source code, but I haven’t solved it yet

**Comment by ZhaoShaw** [comment]
Thanks for your reminder!
This situation may be due to the fact that in the Windows system, pyunpack (0.1.2) does not support calling EasyProcess when unpacking non-zip files.
Since the resource URL provides the download of EEMD zipfile, I made some minor changes.
Thank you again!
